# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  apt_packages:
    - libhdf5-dev
    - libgsl-dev
    - libopenmpi-dev
    - openmpi-bin

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Install the package so autodoc can import Cython extensions
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - dev
