#!/usr/bin/env python

'''
Convert h5 files generated by Chuck for the SPI
A selection file needs to be provided to specify which frames to use.

Needs:
    <h5_fname> - Path to photon-converted h5 file used in SPI
    <sel_name> - Text file containing one entry per line with format <h5_name>_<frame_num>

Produces:
    EMC file with all the single hits in the h5 file
'''

import os
import numpy as np
import h5py
import sys
import logging
#Add utils directory to pythonpath
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
from py_src import writeemc
from py_src import py_utils
from py_src import read_config

if __name__ == '__main__':
    logging.basicConfig(filename='recon.log', level=logging.INFO, format='%(asctime)s - %(levelname)s -%(message)s')
    parser      = py_utils.my_argparser(description='h5toemc')
    parser.add_argument('h5_name', help='HDF5 file to convert to emc format')
    parser.add_argument('sel_name', help='Text file containing list of frames to be converted')
    parser.add_argument('-d', '--dset_name', help='Name of HDF5 dataset containing photon data', default=None)
    args        = parser.special_parse_args()

    logging.info('Starting h5toemc_spigijs....')
    logging.info(' '.join(sys.argv))
    pm          = read_config.get_detector_config(args.config_file, show=args.vb)

    if not os.path.isfile(args.h5_name):
        print 'Data file %s not found. Exiting.' % args.h5_name
        logging.error('Data file %s not found. Exiting.' % args.h5_name)
        sys.exit()

    if not os.path.isfile(args.sel_name):
        print 'Selection file %s not found. Exiting.' % args.sel_name
        logging.error('Selection file %s not found. Exiting.' % args.sel_name)
        sys.exit()

    with open(args.sel_name, 'r') as f:
        ind = np.array([[int(line.split('_')[1]), int(line.rstrip().split('_')[3])] for line in f.readlines()])
    run = int(sys.argv[1].split('_')[1])
    ind = ind[ind[:,0] == run][:,1]

    f = h5py.File(args.h5_name, 'r')
    if args.dset_name is None:
        for name, obj in f['photonConverter'].items():
            try:
                temp = obj.keys()
                dset = obj['photonCount']
                break
            except AttributeError:
                pass
        logging.info('Converting data in '+ dset.name)
    else:
        dset = f[args.dset_name]
        logging.info('Converting data in '+ args.dset_name)
    indarray = np.zeros((dset.shape[0]), dtype='bool')
    indarray[ind] = 1
    frames = dset[indarray,:,:]
    num_frames = len(ind)
    logging.info('%d frames in %s' % (num_frames, args.h5_name))

    emcwriter = writeemc.EMC_writer('data/%s.emc' % os.path.splitext(os.path.basename(sys.argv[1]))[0],
                                    pm['dets_x']*pm['dets_y'])

    for i in range(num_frames):
        emcwriter.write_frame(frames[i].flatten())
        sys.stderr.write('\rFinished %d/%d' % (i+1, num_frames))

    f.close()
    sys.stderr.write('\n')
    emcwriter.finish_write()
